version: "3.7"
services:
  app:
    build: ./app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env.dev
    volumes: ['.:/app']
    command: /usr/local/bin/gunicorn -w 2 -t 3600 -b :8080 app.app:app --reload
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - app:app
